set encoding=utf-8

set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " always display the status line
set autowrite     " automatically :write before running commands
set modelines=0   " disable modelines as a security precaution
set nomodeline

set tabstop=4
set shiftwidth=4
set smartindent
set noexpandtab

" Display extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

" Use one space, not two, after punctuation.
set nojoinspaces


" Make it obvious where 80 characters is
set textwidth=80
set colorcolumn=+1

" Numbers
set number
set numberwidth=5

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

if empty("$XDG_CACHE_HOME")
	let $XDG_CACHE_HOME="$HOME/.cache"
endif

if empty("$XDG_CONFIG_HOME")
	let $XDG_CONFIG_HOME="$HOME/.config"
endif

if empty("$XDG_DATA_HOME")
	let $XDG_DATA_HOME="$HOME/.local/share"
endif

set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set viewdir=$XDG_CACHE_HOME/vim/view,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp

set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

