#!/bin/bash
# Configuration file for bash (~/.bashrc)

main() {

	# shellcheck source=/dev/null
	import() { [ -r "$1" ] && [ -f "$1" ] && source "$1"; }

	if [ -f /etc/bashrc ]; then
		import '/etc/bashrc'
	fi

	local file
	for file in "$HOME"/.bashrc.d/*.bash; do
		import "${file}"
	done
}

if [[ $- == *i* ]]; then
	(main "$@")
fi

unset -f main
